### ISSUE TITLE
Update pinned requirements?

### ISSUE THREAD

**Issue by jsivak** [ncrocfer/whatportis#22]
Howdy,

Can you update your requirements similar to what theblackturtle did in their fork? https://github.com/theblackturtle/whatportis

Pip installing whatportis with other packages in an environment will tend to install the 0.8 version (as Pip tries to satisfy the older requirements specified in the whatportis setup.py).

Thanks.

**Comment by ncrocfer** [comment]
Hi,

I don't understand what you mean by saying "_update your requirements similar to what theblackturtle did_". I just checked the [setup.py of his fork](https://github.com/ncrocfer/whatportis/compare/master...theblackturtle:whatportis:master#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) and he uses `>=` instead of `==`. This is not a good practice, so I will not do it.

Plus you say *installing whatportis with other packages in an environment*, again **this is not a good practice**. I recommend you to install your Python packages in virtual environments, so you will avoid the kind of conflicts you're talking about.

**Comment by jsivak** [comment]
Yeah, I was asking about using ">=" rather than "==" in the setup.py. 
Thanks for considering the request. 
I am using a virtual environment, but am installing several tools in it, so that is how I bumped into this issue.
